### PR TITLE
Add nautilus extension

### PR DESCRIPTION
**Pull request by malfisya**
**Summary**

Add nautilus extension. The code is mostly taken from similiar project called "Snoop" with modifications to fit Clapgrep.

**Picture**

https://files.catbox.moe/nnwakz.png

### CODE REVIEW

**Comment by malfisya** [comment]
I know this is not in your [roadmap](https://github.com/luleyleo/clapgrep/issues/39), but I just feel the need to share it with you. The code is mostly taken from [Snoop extension](https://gitlab.gnome.org/philippun1/snoop/-/blob/main/extension/snoop.py?ref_type=heads). I don't know if it violates the license agreement, if it does I will close this. Thank you and sorry in advance. Cheers!

**Comment by luleyleo** [comment]
Does the extension work for you? Could you share a screenshot of what I should expect? Because neither this nor the Snoop one seem to do anything for me.

**Comment by malfisya** [comment]
It works for me. The extension should be put in `~/.local/share/nautilus-python/extensions`. I attached a link to screenshot in my original message. Here is a video:

[Screencast From 2024-11-20 20-49-34.webm](https://github.com/user-attachments/assets/1ad41e23-3712-434e-a526-b1a8498c88b4)

**Comment by malfisya** [comment]
Gnome 47 and Nautilus 47. Did you have `nautilus-extension` and `nautilus-python` installed? It honestly just works for me. I don't know how relevant this is, but this is my system specs: 
# System Details Report
---

## Report details
- **Date generated:**                              2024-11-21 10:51:16

## Hardware Information:
- **Hardware Model:**                              empty empty
- **Memory:**                                      16.0 GiB
- **Processor:**                                   Intel® Core™ i5-3570K × 4
- **Graphics:**                                    AMD Radeon™ RX 550 / 550 Series
- **Disk Capacity:**                               752.2 GB

## Software Information:
- **Firmware Version:**                            4.6.5
- **OS Name:**                                     Solus 4.6 Convergence
- **OS Build:**                                    (null)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               47
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.11.7-309.current

**Comment by luleyleo** [comment]
Ah, I was missing `nautilus-python`! Now it's working.

This seems a bit more discoverable than the "Open > Open With > Clapgrep" flow.

**Pull request merged**
